import type { AdmissionRecord, Department, University } from "./types";

/**
 * 수도권(경기·인천) 2026 결과 연결용 데이터.
 * 숫자는 공식 대입정보포털에서 확인된 공개값만 기록하며,
 * 확인되지 않은 모집단위의 컷은 추정하지 않는다.
 */
export const METRO_2026_EXPANSION_UNIVERSITIES: University[] = [
  { id: "gg_ajou", name: "아주대학교", region: "경기", location: "수원" },
  { id: "gg_kyonggi", name: "경기대학교", region: "경기", location: "수원" },
  { id: "ic_inha", name: "인하대학교", region: "인천", location: "인천" },
  { id: "gg_suwon", name: "수원대학교", region: "경기", location: "화성" },
];

export const METRO_2026_EXPANSION_DEPARTMENTS: Department[] = [];

export const METRO_2026_EXPANSION_ADMISSIONS: AdmissionRecord[] = [
  {
    id: "ajou_2026_top10_essay_medical",
    universityId: "gg_ajou",
    departmentId: "ajou_medical",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 10,
    competitionRate: 183.1,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_pharmacy",
    universityId: "gg_ajou",
    departmentId: "ajou_pharmacy",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 5,
    competitionRate: 708.2,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_business",
    universityId: "gg_ajou",
    departmentId: "ajou_business",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 16,
    competitionRate: 106.63,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_economics",
    universityId: "gg_ajou",
    departmentId: "ajou_econ_politics",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 5,
    competitionRate: 101.6,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_korean",
    universityId: "gg_ajou",
    departmentId: "ajou_korean",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 5,
    competitionRate: 96.4,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_free_human",
    universityId: "gg_ajou",
    departmentId: "ajou_free_human",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 5,
    competitionRate: 109.2,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_free_natural",
    universityId: "gg_ajou",
    departmentId: "ajou_free_natural",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 10,
    competitionRate: 51.1,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_mech",
    universityId: "gg_ajou",
    departmentId: "ajou_mech",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 5,
    competitionRate: 49.8,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_elec",
    universityId: "gg_ajou",
    departmentId: "ajou_elec",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 37,
    competitionRate: 48.84,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "ajou_2026_top10_essay_semiconductor",
    universityId: "gg_ajou",
    departmentId: "ajou_semiconductor",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자전형",
    quota: 12,
    competitionRate: 45.25,
    source: "대입정보포털 어디가 2027 아주대학교 대학정보",
    verified: true,
  },
  {
    id: "inha_2026_top_essay_medical",
    universityId: "ic_inha",
    departmentId: "inha_medical",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자-의예과",
    quota: 8,
    competitionRate: 276.13,
    source: "대입정보포털 어디가 2027 인하대학교 대학정보",
    verified: true,
  },
  {
    id: "inha_2026_top_essay_social_education",
    universityId: "ic_inha",
    departmentId: "inha_social_education",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자",
    quota: 3,
    competitionRate: 45.67,
    source: "대입정보포털 어디가 2027 인하대학교 대학정보",
    verified: true,
  },
  {
    id: "inha_2026_top_essay_media",
    universityId: "ic_inha",
    departmentId: "inha_media",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자",
    quota: 7,
    competitionRate: 45.43,
    source: "대입정보포털 어디가 2027 인하대학교 대학정보",
    verified: true,
  },
  {
    id: "inha_2026_top_essay_social_welfare",
    universityId: "ic_inha",
    departmentId: "inha_social_welfare",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자",
    quota: 4,
    competitionRate: 39.75,
    source: "대입정보포털 어디가 2027 인하대학교 대학정보",
    verified: true,
  },
  {
    id: "inha_2026_top_essay_business",
    universityId: "ic_inha",
    departmentId: "inha_business",
    academicYear: 2026,
    type: "논술",
    name: "논술우수자",
    quota: 22,
    competitionRate: 39.41,
    source: "대입정보포털 어디가 2027 인하대학교 대학정보",
    verified: true,
  },
  {
    id: "gg_kyonggi_2026_top_social_care",
    universityId: "gg_kyonggi",
    departmentId: "gg_kyonggi_social_care",
    academicYear: 2026,
    type: "학종",
    name: "학생부종합(사회배려대상자전형)",
    quota: 2,
    competitionRate: 39.5,
    source: "대입정보포털 어디가 2027 경기대학교 대학정보",
    verified: true,
  },
  {
    id: "gg_kyonggi_2026_top_public_safety",
    universityId: "gg_kyonggi",
    departmentId: "gg_kyonggi_public_safety",
    academicYear: 2026,
    type: "학종",
    name: "학생부종합(사회배려대상자전형)",
    quota: 2,
    competitionRate: 37,
    source: "대입정보포털 어디가 2027 경기대학교 대학정보",
    verified: true,
  },
];
