import type { Admission, Department, University } from "./types";

/**
 * 2027학년도 서울·경기·인천 핵심 전형의 공식 공개자료 기반 seed.
 * 출처: 대입정보포털 어디가 2027 대학별 전형평가기준.
 * 입결 숫자는 별도 검증 전까지 넣지 않는다.
 */
export const metro2027Universities: University[] = [
  { id: "korea", name: "고려대학교", region: "서울" },
  { id: "ewha", name: "이화여자대학교", region: "서울" },
  { id: "ssu", name: "숭실대학교", region: "서울" },
  { id: "inha", name: "인하대학교", region: "인천" },
];

export const metro2027Departments: Department[] = [
  { id: "korea-cs", universityId: "korea", name: "컴퓨터학과", category: "자연계" },
  { id: "ewha-cs", universityId: "ewha", name: "컴퓨터공학과", category: "자연계" },
  { id: "ssu-cs", universityId: "ssu", name: "컴퓨터학부", category: "자연계" },
  { id: "inha-mechanical", universityId: "inha", name: "기계공학과", category: "자연계" },
];

export const metro2027Admissions: Admission[] = [
  {
    id: "korea-academic-2027",
    universityId: "korea",
    departmentId: "korea-cs",
    academicYear: 2027,
    name: "학업우수전형",
    type: "학종",
    recruitmentCount: 871,
    documentWeight: 100,
    csatMinimum: { enabled: true, description: "수능최저 적용. 모집단위별 세부 기준은 공식 모집요강 확인." },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000069", academicYear: 2027, confidence: 0.98 },
    isMock: false,
  },
  {
    id: "korea-kyoyeol-2027",
    universityId: "korea",
    departmentId: "korea-cs",
    academicYear: 2027,
    name: "계열적합전형",
    type: "학종",
    recruitmentCount: 530,
    documentWeight: 60,
    interview: true,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000069", academicYear: 2027, confidence: 0.98 },
    isMock: false,
  },
  {
    id: "ewha-future-document-2027",
    universityId: "ewha",
    departmentId: "ewha-cs",
    academicYear: 2027,
    name: "미래인재전형-서류형",
    type: "학종",
    recruitmentCount: 909,
    documentWeight: 100,
    csatMinimum: { enabled: true, description: "자연계열: 국어·수학·영어·탐구 중 수학 포함 2개 영역 등급 합 5 이내. 모집단위별 예외는 공식 자료 확인." },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000163", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "ewha-future-interview-2027",
    universityId: "ewha",
    departmentId: "ewha-cs",
    academicYear: 2027,
    name: "미래인재전형-면접형",
    type: "학종",
    recruitmentCount: 209,
    documentWeight: 70,
    interview: true,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000163", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "ssu-future-interview-2027",
    universityId: "ssu",
    departmentId: "ssu-cs",
    academicYear: 2027,
    name: "SSU 미래인재전형(면접형)",
    type: "학종",
    recruitmentCount: 522,
    documentWeight: 50,
    interview: true,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000143", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "ssu-future-document-2027",
    universityId: "ssu",
    departmentId: "ssu-cs",
    academicYear: 2027,
    name: "SSU 미래인재전형(서류형)",
    type: "학종",
    recruitmentCount: 163,
    documentWeight: 100,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000143", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "ssu-sw-2027",
    universityId: "ssu",
    departmentId: "ssu-cs",
    academicYear: 2027,
    name: "SW 우수자전형",
    type: "학종",
    recruitmentCount: 17,
    documentWeight: 50,
    interview: true,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000143", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "ssu-grade-2027",
    universityId: "ssu",
    departmentId: "ssu-cs",
    academicYear: 2027,
    name: "교과우수자",
    type: "교과",
    recruitmentCount: 464,
    studentRecordWeight: 100,
    csatMinimum: { enabled: true, description: "국어·수학·영어·사회/과학탐구 중 2개 영역 등급 합 6 이내." },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000143", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "inha-future-interview-2027",
    universityId: "inha",
    departmentId: "inha-mechanical",
    academicYear: 2027,
    name: "인하미래인재(면접형)",
    type: "학종",
    recruitmentCount: 939,
    documentWeight: 70,
    interview: true,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000169", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "inha-future-document-2027",
    universityId: "inha",
    departmentId: "inha-mechanical",
    academicYear: 2027,
    name: "인하미래인재(서류형)",
    type: "학종",
    recruitmentCount: 261,
    documentWeight: 100,
    csatMinimum: { enabled: false },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000169", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
  {
    id: "inha-region-2027",
    universityId: "inha",
    departmentId: "inha-mechanical",
    academicYear: 2027,
    name: "학생부교과(지역균형)",
    type: "교과",
    recruitmentCount: 438,
    studentRecordWeight: 100,
    csatMinimum: { enabled: true, description: "인문 2개 영역 합 6, 자연(의예 제외) 2개 영역 합 5, 의예 3개 영역 합 4 등급 이내." },
    source: { type: "adiga", url: "https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000169", academicYear: 2027, confidence: 0.99 },
    isMock: false,
  },
];
